apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc-twitter
  namespace: twitter
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 300Mi
