apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc-twitter
  namespace: twitter
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 300Mi
