FROM bitnami/openldap:2.6
MAINTAINER soroosh.mehmandoost@gmail.com

ENV LDAP_ADMIN_USERNAME=admin
ENV LDAP_ADMIN_PASSWORD=admin
ENV LDAP_USERS=user1,user2
ENV LDAP_PASSWORDS=qazwsx,qazwsx
ENV LDAP_ROOT=dc=soroosh,dc=land
ENV LDAP_ADMIN_DN=cn=admin,dc=soroosh,dc=land

EXPOSE 1389
